/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardSubjectsRouteImport } from './routes/dashboard.subjects'
import { Route as DashboardStudentsRouteImport } from './routes/dashboard.students'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardProjectWorkRouteImport } from './routes/dashboard.project-work'
import { Route as DashboardMarksRouteImport } from './routes/dashboard.marks'
import { Route as DashboardDistributorRouteImport } from './routes/dashboard.distributor'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSubjectsRoute = DashboardSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudentsRoute = DashboardStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectWorkRoute = DashboardProjectWorkRouteImport.update({
  id: '/project-work',
  path: '/project-work',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMarksRoute = DashboardMarksRouteImport.update({
  id: '/marks',
  path: '/marks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDistributorRoute = DashboardDistributorRouteImport.update({
  id: '/distributor',
  path: '/distributor',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/distributor': typeof DashboardDistributorRoute
  '/dashboard/marks': typeof DashboardMarksRoute
  '/dashboard/project-work': typeof DashboardProjectWorkRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/students': typeof DashboardStudentsRoute
  '/dashboard/subjects': typeof DashboardSubjectsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/distributor': typeof DashboardDistributorRoute
  '/dashboard/marks': typeof DashboardMarksRoute
  '/dashboard/project-work': typeof DashboardProjectWorkRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/students': typeof DashboardStudentsRoute
  '/dashboard/subjects': typeof DashboardSubjectsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/distributor': typeof DashboardDistributorRoute
  '/dashboard/marks': typeof DashboardMarksRoute
  '/dashboard/project-work': typeof DashboardProjectWorkRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/students': typeof DashboardStudentsRoute
  '/dashboard/subjects': typeof DashboardSubjectsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/distributor'
    | '/dashboard/marks'
    | '/dashboard/project-work'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/students'
    | '/dashboard/subjects'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/distributor'
    | '/dashboard/marks'
    | '/dashboard/project-work'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/students'
    | '/dashboard/subjects'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/distributor'
    | '/dashboard/marks'
    | '/dashboard/project-work'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/students'
    | '/dashboard/subjects'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/subjects': {
      id: '/dashboard/subjects'
      path: '/subjects'
      fullPath: '/dashboard/subjects'
      preLoaderRoute: typeof DashboardSubjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/students': {
      id: '/dashboard/students'
      path: '/students'
      fullPath: '/dashboard/students'
      preLoaderRoute: typeof DashboardStudentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/project-work': {
      id: '/dashboard/project-work'
      path: '/project-work'
      fullPath: '/dashboard/project-work'
      preLoaderRoute: typeof DashboardProjectWorkRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/marks': {
      id: '/dashboard/marks'
      path: '/marks'
      fullPath: '/dashboard/marks'
      preLoaderRoute: typeof DashboardMarksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/distributor': {
      id: '/dashboard/distributor'
      path: '/distributor'
      fullPath: '/dashboard/distributor'
      preLoaderRoute: typeof DashboardDistributorRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardDistributorRoute: typeof DashboardDistributorRoute
  DashboardMarksRoute: typeof DashboardMarksRoute
  DashboardProjectWorkRoute: typeof DashboardProjectWorkRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardStudentsRoute: typeof DashboardStudentsRoute
  DashboardSubjectsRoute: typeof DashboardSubjectsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDistributorRoute: DashboardDistributorRoute,
  DashboardMarksRoute: DashboardMarksRoute,
  DashboardProjectWorkRoute: DashboardProjectWorkRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardStudentsRoute: DashboardStudentsRoute,
  DashboardSubjectsRoute: DashboardSubjectsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
